name: Deploy to EC2
on:
  workflow_run:
    workflows: [".NET"] # Replace with the name of your CI workflow file if different
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sync code to server
        run: |
         
          sudo rsync -av --delete ./ /var/www/api  # Sync code to the desired directory
      - name: Switch to 'Production' branch on server
        run: |
          cd /var/www/api
          git fetch  # Fetch latest branches and commits
          git checkout Production  # Switch to Production branch
          git pull origin Production  # Pull the latest code from Production branch
          

      - name: Restart your service (if needed)
        run: |
          sudo systemctl restart myapi.service  # Optional: restart the service if required
